agent_decision_mode: heuristic
enable_monitoring: false
experiment_id: baseline_raft_0005_00
fault_intensity: none
fault_scenarios:
- none
job_arrival_pattern: medium
methods:
- raft
num_agents: 5
output_dir: experimental_campaign_results/unknown/raw_data
save_detailed_logs: true
simulation_time: 300
specialization_level: 0.0
workload_profile: mixed
